### PR TITLE
Updated the burn function and constructor

### PR DESCRIPTION
**Pull request by ibrahim1023**
Sorry I forgot to add the override keyword

### CODE REVIEW

**Comment by chrishobcroft** [comment]
Can I ask why you chose to require a `burner` address in the constructor, when both other roles are given to `msg.sender` by default?

```
    constructor(address burner) ERC721("Participant Access Token", "PAT") {
        _setupRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _setupRole(MINTER_ROLE, msg.sender);
        _setupRole(BURNER_ROLE, burner);
    }
```

**Comment by ibrahim1023** [comment]
I thought it would make sense to give the burner role to a different individual

**Comment by chrishobcroft** [comment]
@ibrahim1023 are you participating in the HackMoney hackathon?

**Comment by ibrahim1023** [comment]
Nope never heard of it. Would love to take part in something exciting xD

**Comment by chrishobcroft** [comment]
More details are [here](https://defi.ethglobal.co/). Sadly I think that applications are closed now because the hackathon started 8 days ago.

Keep and eye out for other hackathons though, at [ETHGlobal's homepage](https://ethglobal.co/).

**Pull request merged**
